### ISSUE TITLE
Timing in timed test lists not applied per test

### ISSUE THREAD

**Issue by thiagomacieira** [opendcdiag/opendcdiag#533]
Given
```
$ cat testlist
selftest_timedpass:10
selftest_timedpass:150
$ ./opendcdiag --selftests -o - --test-list-file testlist
```

Before e89cd594fcda062209c3fccf7fa7a34bbe62b58f:
```yaml
tests:
- test: selftest_timedpass
  details: { quality: beta, description: "Loops around usleep() for the regular test time" }
  state: { seed: 'AES:6191e47dc78fde56624e4f956cd34fa79e6e1b82387021a99db1b06a932cb058', iteration: 0, retry: false }
  time-at-start: { elapsed:      0.000, now: !!timestamp '2024-07-19T15:36:06Z' }
  result: pass
  time-at-end:   { elapsed:     11.999, now: !!timestamp '2024-07-19T15:36:06Z' }
  test-runtime: 12.626
- test: selftest_timedpass
  details: { quality: beta, description: "Loops around usleep() for the regular test time" }
  state: { seed: 'AES:16ac70e7a580c1b6a0dd66f99c6825609e6e1b82387021a99db1b06a932cb058', iteration: 0, retry: false }
  time-at-start: { elapsed:     18.999, now: !!timestamp '2024-07-19T15:36:06Z' }
  result: pass
  time-at-end:   { elapsed:    170.998, now: !!timestamp '2024-07-19T15:36:06Z' }
  test-runtime: 153.249
# Loop iteration 1 finished, average time 177.52 ms, total 177.52 ms
- test: mce_check
  details: { quality: production, description: "Machine Check Exceptions/Events count" }
  state: { seed: 'AES:bf2d9c0ec73a3f6e966665d97ddabfe19e6e1b82387021a99db1b06a932cb058', iteration: 0, retry: false }
  time-at-start: { elapsed:    170.998, now: !!timestamp '2024-07-19T15:36:06Z' }
  result: pass
  time-at-end:   { elapsed:    173.998, now: !!timestamp '2024-07-19T15:36:06Z' }
  test-runtime: 3.014
exit: pass
```

After:
```yaml
tests:
- test: selftest_timedpass
  details: { quality: beta, description: "Loops around usleep() for the regular test time" }
  state: { seed: 'AES:fffc3604d9ed0812a430e2fd185cec390003c9fb2612f7ed5bcf1d02e7a313c6', iteration: 0, retry: false }
  time-at-start: { elapsed:      0.000, now: !!timestamp '2024-07-19T15:33:02Z' }
  result: pass
  time-at-end:   { elapsed:    160.000, now: !!timestamp '2024-07-19T15:33:02Z' }
  test-runtime: 158.627
- test: selftest_timedpass
  details: { quality: beta, description: "Loops around usleep() for the regular test time" }
  state: { seed: 'AES:591e97287c944c87dbd4541f097192020003c9fb2612f7ed5bcf1d02e7a313c6', iteration: 0, retry: false }
  time-at-start: { elapsed:    163.333, now: !!timestamp '2024-07-19T15:33:02Z' }
  result: pass
  time-at-end:   { elapsed:    326.667, now: !!timestamp '2024-07-19T15:33:02Z' }
  test-runtime: 160.658
# Loop iteration 1 finished, average time 325.254 ms, total 325.254 ms
exit: pass
```

The lack of `mce_check` is irrelevant for now.

The timing of 150 ms was applied to both runs of the test, not to each test like it used to be.
