### ISSUE TITLE
Add a way to include non-text fields in the log

### ISSUE THREAD

**Issue by thiagomacieira** [opendcdiag/opendcdiag#559]
For example, the IFS test could the failure information as in:
```yaml
  - thread: 2
    id: { logical: 1, package: 0, core: 1, thread: 0, family: 6, model: 0x8c, stepping: 1, microcode: 0xb8, ppin: null }
    state: failed
    time-to-fail: 102.416
    loop-count: 0
    messages:
    - level: error
      text: 'E> Test "intel_ifs_0" failed'
      details:
        condition: 0x1234
        image: 0x1
        version: 0x1
```
instead of
```yaml
  - thread: 2
    id: { logical: 1, package: 0, core: 1, thread: 0, family: 6, model: 0x8c, stepping: 1, microcode: 0xb8, ppin: null }
    state: failed
    time-to-fail: 102.416
    loop-count: 0
    messages:
    - { level: error, text: 'E> Test "intel_ifs_0" failed with condition: 0x1234 image: 0x1 version: 0x1' }
```

That's far more machine-readable than scraping logs.
