### ISSUE TITLE
Crash on second or further slices are reported as timeouts

### ISSUE THREAD

**Issue by thiagomacieira** [opendcdiag/opendcdiag#571]
When a second or later child process crashes, the backtrace is shown for the first ("main") child and the actual crashing child is reported as a timeout.

Test:
```yaml
command-line: 'opendcdiag --selftests -e selftest_sigsegv --max-cores-per-slice=1 --cpuset=c0,c1 --retest-on-failure=0 -o - --timeout=5s'
version: opendcdiag-17b9501e6ed0-dirty
os: Linux 6.11.8-1-default, glibc 2.40, OpenSSL 3.2.3 3 Sep 2024
timing: { duration: 1000.000, timeout: 5000.000 }
cpu-info:
  0: { logical: 0, package: 0, core: 0, thread: 0, family: 6, model: 0x8c, stepping: 1, microcode: 0xb8, ppin: null }
  1: { logical: 4, package: 0, core: 0, thread: 1, family: 6, model: 0x8c, stepping: 1, microcode: 0xb8, ppin: null }
  2: { logical: 1, package: 0, core: 1, thread: 0, family: 6, model: 0x8c, stepping: 1, microcode: 0xb8, ppin: null }
  3: { logical: 5, package: 0, core: 1, thread: 1, family: 6, model: 0x8c, stepping: 1, microcode: 0xb8, ppin: null }
test-plans:
  fullsocket: [ { starting_cpu: 0, count: 4 } ]
  heuristic: [ { starting_cpu: 0, count: 2 }, { starting_cpu: 2, count: 2 } ]
tests:
- test: selftest_sigsegv
  time-at-start: { elapsed:      0.000, now: !!timestamp '2024-12-10T18:29:13Z' }
  result: timed out
  fail: { cpu-mask: '22', time-to-fail: null, seed: 'AES:a12be72ca820b2d74a454264e9ab43cf5ed418d357df4d28b5babd9b1654bc30'}
  time-at-end:   { elapsed:   5163.363, now: !!timestamp '2024-12-10T18:29:18Z' }
  test-runtime: 5163.457
  threads:
  - thread: main
    runtime: 1214.951
    resource-usage: { utime: 1.062, stime: 0.000, cpuavg: 0.1, maxrss: 3696, majflt: 0, minflt: 76, voluntary-cs: 11, involutary-cs: 2 }
    messages:
    - level: info
      text: |1
       Backtrace:
       Thread 3 (Thread 0x7fb491bfc6c0 (LWP 761380) "selftest_sigseg"):
       #0  0x00007fb492d1b16d in syscall () from /lib64/libc.so.6
       #1  0x000000000049d302 in futex (uaddr=0x7fb493ba9040, futex_op=0, val=2, timeout=0x0, uaddr2=0x0, val3=0) at ../../../src/arkose/arkose-one/opendcdiag/framework/sysdeps/linux/futex.h:21
       #2  0x000000000049d33c in futex_wait (ptr=0x7fb493ba9040, expected=2) at ../../../src/arkose/arkose-one/opendcdiag/framework/sysdeps/linux/futex.h:26
       #3  0x000000000049d563 in child_crash_handler (si=0x7fb491bfb170, ucontext=0x7fb491bfb040) at ../../../src/arkose/arkose-one/opendcdiag/framework/sysdeps/unix/child_debug.cpp:211
               thread_state = std::atomic<ThreadState> = { thread_failed }
               socket = 4
               in_crash_handler = {<std::__atomic_flag_base> = {_M_i = true}, <No data fields>}
               dummy = {fd = 0, events = 0, revents = 0}
       #4  <signal handler called>
       [rest of the backtrace trimmed]
    - { level: info, text: 'Backtrace:' }
  - thread: main 1
    runtime: 5163.377
    resource-usage: { utime: 0.891, stime: 0.000, cpuavg: 0.0, maxrss: 3760, majflt: 0, minflt: 81, voluntary-cs: 17, involutary-cs: 3 }
    messages:
    - { level: error, text: 'E> Child 761376 did not exit, sending signal SIGQUIT' }
  - thread: 1
    id: { logical: 4, package: 0, core: 0, thread: 1, family: 6, model: 0x8c, stepping: 1, microcode: 0xb8, ppin: null }
    state: failed
    time-to-fail: 12.543
    loop-count: 0
    freq_mhz: 0.0
    messages:
    - { level: error, text: 'E> Received signal 11 (Segmentation fault) code=1 (SEGV_MAPERR), RIP = 0x4990d5 (opendcdiag+0x990d5), CR2 = 0x33, trap=14 (PF), error_code = 0x4' }
    - { level: error, text: 'E> Thread is stuck' }
  - thread: 3
    id: { logical: 5, package: 0, core: 1, thread: 1, family: 6, model: 0x8c, stepping: 1, microcode: 0xb8, ppin: null }
    state: failed
    time-to-fail: 12.059
    loop-count: 0
    freq_mhz: 0.0
    messages:
    - { level: error, text: 'E> Received signal 11 (Segmentation fault) code=1 (SEGV_MAPERR), RIP = 0x4990d5 (opendcdiag+0x990d5), CR2 = 0x3ac, trap=14 (PF), error_code = 0x4' }
    - { level: error, text: 'E> Thread is stuck' }
exit: invalid
```

The backtrace is shown under the first child ("main") and the second child ("main 1") is shown as timed out - the framework sent a SIGQUIT and the log shows it ran for 5.1 seconds and yet used only 0.9 ms of CPU time. The backtrace clearly shows the child is stopped in `futex_wait` at:
https://github.com/opendcdiag/opendcdiag/blob/b8bdda557a388a06d66eb6a9d4455263a56e472b/framework/sysdeps/unix/child_debug.cpp#L209-L210

But the parent never wakes this child. The code in `debug_crashed_child` was never updated to find which child had crashed:
https://github.com/opendcdiag/opendcdiag/blob/b8bdda557a388a06d66eb6a9d4455263a56e472b/framework/sysdeps/unix/child_debug.cpp#L1047-L1053
